export const example = [{
  dateModified: null,
  idMeal: "52787",
  strArea: "American",
  strCategory: "Dessert",
  strDrinkAlternate: null,
  strIngredient1: "Chocolate Chips",
  strIngredient2: "Heavy Cream",
  strIngredient3: "Condensed Milk",
  strIngredient4: "Vanilla Extract",
  strIngredient5: "White Chocolate Chips",
  strIngredient6: "Miniature Marshmallows",
  strIngredient7: "",
  strIngredient8: "",
  strIngredient9: "",
  strIngredient10: "",
  strIngredient11: "",
  strIngredient12: "",
  strIngredient13: "",
  strIngredient14: "",
  strIngredient15: "",
  strIngredient16: "",
  strIngredient17: "",
  strIngredient18: "",
  strIngredient19: "",
  strIngredient20: "",
  strInstructions: "Line an 8-inch-square baking pan with wax paper or foil, and coat with non-stick spray. In a microwave-safe bowl, combine the dark chocolate chips, heavy cream and half of the sweetened condensed milk. Microwave the dark chocolate mixture in 20-second intervals, stirring in between each interval, until the chocolate is melted. Add the vanilla extract to the dark chocolate mixture and stir well until smooth. Transfer the dark chocolate mixture into the prepared pan and spread into an even layer. In a separate bowl, combine the white chocolate chips with the remaining half of the sweetened condensed milk. Microwave the white chocolate mixture in 20-second intervals, stirring in between each interval, until the chocolate is melted. Evenly spread the white chocolate mixture on top of dark chocolate layer. Top the chocolate layers with the Mallow Bits or miniature marshmallows, and gently press them down. Refrigerate for 4 hours, or until set. Remove the fudge and wax paper from the pan. Carefully peel all of the wax paper from the fudge. Cut the fudge into bite-sized pieces and serve.",
  strMeal: "Hot Chocolate Fudge",
  strMealThumb: "https://www.themealdb.com/images/media/meals/xrysxr1483568462.jpg",
  strMeasure1: "2 cups",
  strMeasure2: "2 tbs",
  strMeasure3: "1 – 14-ounce can",
  strMeasure4: "1 tsp",
  strMeasure5: "1-⅓ cups",
  strMeasure6: "1-½ cups",
  strMeasure7: "",
  strMeasure8: "",
  strMeasure9: "",
  strMeasure10: "",
  strMeasure11: "",
  strMeasure12: "",
  strMeasure13: "",
  strMeasure14: "",
  strMeasure15: "",
  strMeasure16: "",
  strMeasure17: "",
  strMeasure18: "",
  strMeasure19: "",
  strMeasure20: "",
  strSource: "",
  strTags: "Snack,Chocolate",
  strYoutube: "https://www.youtube.com/watch?v=oJvbsVSblfk"
}]